### ISSUE TITLE
Where is pre-compiled packages?

### ISSUE THREAD

**Issue by KirbyJoe** [Tiehuis/HeborisC7EX#2]
Hello,
I want to ask where I can find a pre-compiled packages of Heboris C7EX in GitHub.
The readme in a Heboris repository has a description about pre-compiled packages:

> Note, if you don't wish to compile heboris, then the runtime packages only are required. See the releases section for pre-compiled packages.

But I can't find these packages on the release section (also, there aren't any releases in this repository). Are you haven't uploaded a pre-compiled packages of Heboris yet?

Thank you.

**Comment by tiehuis** [comment]
I did write that, didn't I. I think I changed my mind on this someway through and forgot to update the readme, sorry. The main reasoning is that providing packages for the different linux distributions is a bit involved and I think that the program itself is pretty straight-forward to compile.

For windows packages, I know there were some executables around on the internet, but I don't plan on putting those on this page.

I'll update the readme so this is clearer.
